---
title: "Final Submition"
output: pdf_document
date: "2024-08-20"
---

```{r}
library(tidyverse)
library(ggplot2)
genes <- read.csv("QBS103_GSE157103_genes.csv")
matrix <- read.csv("QBS103_GSE157103_series_matrix.csv")

id_genes <- colnames(genes)
id_genes <- id_genes[-1]
id_matrix <- matrix$participant_id
diff1 <- setdiff(id_genes, id_matrix)
diff2 <- setdiff(id_matrix, id_genes)
colnames(genes)[colnames(genes) == diff1] <- diff2
matrix <- matrix %>% rename('procalcitonin.ng.ml.' = 'procalcitonin.ng.ml..')

unknown_id <- matrix$'participant_id'[matrix$sex == ' unknown']

matrix <- matrix[!matrix$participant_id %in% unknown_id, ]
genes[[unknown_id]] <- NULL
```
Generate a table formatted in LaTeX of summary statistics for all the covariates you looked at and 2 additional continuous (3 total) and 1 additional categorical variable (3 total). (5 pts)
```{r}
### Define the item we need to use and the function data type
selected_item <- c("age", "ferritin.ng.ml.", "procalcitonin.ng.ml.", "sex", "disease_status" , "icu_status" )
numeric_item <- c("age", "ferritin.ng.ml.", "procalcitonin.ng.ml.")
category_item <- c("sex", "disease_status" , "icu_status")
continous_item <- c("age", "ferritin.ng.ml.", "procalcitonin.ng.ml.")

table_generate <- function(matrix, selected_item){
  selected_item <- unlist(selected_item, numeric_item)
  selected_matrix <- matrix[,c('participant_id', selected_item)]
  for(item in numeric_item){
  selected_matrix[[item]] = as.numeric(as.character(selected_matrix[[item]]))    
  }
  return(selected_matrix)
}

selected_table <- table_generate(matrix, selected_item)

```

```{r}
summary_sex <- selected_table %>%
  group_by(sex) %>%
  summarise(
    count = n()
  )

summary_disease <- selected_table %>%
  group_by(disease_status) %>%
  summarise(
    Count = n(),
    Percentage = round(100 * n() / nrow(.), 1),
  )

summary_disease_male <- selected_table %>%
  filter(sex == " male") %>% 
  group_by(disease_status) %>%
  summarise(
    Count = n(),
    Percentage = round(100 * n() / nrow(.), 1),
    Total = nrow(.)
  )

summary_disease_female <- selected_table %>%
  filter(sex == " female") %>%
  group_by(disease_status) %>%
  summarise(
    Count = n(),
    Percentage = round(100 * n() / nrow(.), 1),
    Total = nrow(.)
  )

summary_icu <- selected_table %>%
  group_by(icu_status) %>%
  summarise(
    Count = n(),
    Percentage = round(100 * n() / nrow(.), 1),
  )

summary_icu_male <- selected_table %>%
  filter(sex == " male") %>%
  group_by(icu_status) %>%
  summarise(
    Count = n(),
    Percentage = round(100 * n() / nrow(.), 1),
    Total = nrow(.)
  )

summary_icu_female <- selected_table %>%
  filter(sex == " female") %>%
  group_by(icu_status) %>%
  summarise(
    Count = n(),
    Percentage = round(100 * n() / nrow(.), 1),
    Total = nrow(.)
  )

summary_table <- selected_table %>%
  select(c(continous_item, 'sex')) %>%
  group_by(sex) %>%
  summarise(
    across(where(is.numeric), list(
      mean = ~mean(.x, na.rm = TRUE),
      sd = ~sd(.x, na.rm=TRUE),
      max = ~max(.x, na.rm = TRUE),
      min = ~min(.x, na.rm = TRUE),
      median = ~median(.x, na.rm = TRUE)
    ), .names = "{fn}_{col}")
  )

summary_table_all <- selected_table %>%
  select(c(continous_item, 'sex')) %>%
  summarise(
    across(where(is.numeric), list(
      mean = ~mean(.x, na.rm = TRUE),
      sd = ~sd(.x, na.rm=TRUE),
      max = ~max(.x, na.rm = TRUE),
      min = ~min(.x, na.rm = TRUE),
      median = ~median(.x, na.rm = TRUE)
    ), .names = "{fn}_{col}")
  )


```


```{r}
plot_create <- function(genes, matrix, gene){
  genes_long <- genes %>%
    filter(X==gene) %>%
    gather(key = "participant_id")
  genes_long <- genes_long[-1,]

  plot_data <- merge(matrix, genes_long, by = "participant_id")
  plot_data$value <- as.numeric(as.character(plot_data$value))
  
  
  frequency_plot <-
    ggplot(plot_data, aes(x=value)) + 
    geom_histogram(binwidth=1, fill="#48a2c8", color="#19d9d9") + 
    ggtitle(paste("Histogram of Values of ", gene)) + 
    xlab("Value") + 
    ylab("Frequency")
  
  continuous_plot <-
    ggplot(plot_data, aes(x=age, y=value)) +
    geom_point(aes(color=age)) + 
    scale_color_gradient(low="#EE3D59", high="#F5C518") +
    ggtitle(paste("Scatterplot of ", gene, " gene vs. Age")) +
    xlab("age") +
    ylab("Value") +
    theme_minimal()
  
  categorical_plot <-
    ggplot(plot_data, aes(x = icu_status, y = value, fill = sex)) +
    geom_boxplot(notch = TRUE) +
    ggtitle(paste("Gene Value of ", gene," by icu status and sex") )+
    xlab("icu status") +
    ylab("Gene Value") +
    scale_fill_manual(values = c(" male" = "#1f77b4", " female" = "#ff69b4")) +
    theme_minimal()
  
  
  return (list(frequency_plot, continuous_plot, categorical_plot))
}
```


```{r}
plots = plot_create(genes, selected_table, "AAMP")
print(plots)
```

```{r}
library(pheatmap)

gene_select = c("AAGAB", "AAMP", "AATF", "ABCA1", "ABCA2", "ABCA7", "ABCC5", "ABCG1", "ABCE1", "ABCF1", "ABCF3", "ABHD10")

annotation <- data.frame(
  participant_id = factor(matrix$participant_id),
  sex = factor(matrix$sex),
  icu_status = factor(matrix$icu_status)
)
rownames(annotation) <- annotation[,1]
annotation <- annotation[,-1]


gene_selected_data <- genes%>%
  filter(X %in% gene_select)
rownames(gene_selected_data) <- gene_selected_data[,1]
gene_selected_data <- gene_selected_data[,-1]

annotation_color <- list(
  sex = c(' female' = '#ff69b4',
          ' male' = '#1f77b4')
)
pheatmap(gene_selected_data,
         cluster_rows = T,
         cluster_cols = T,
         annotation_col = annotation,
         annotation_colors = annotation_color,
         show_colnames = FALSE,
         main = "Heatmap of Selected Genes",
         legend_labels = "Gene Value")
```

```{r}
selected_table %>%
  ggplot(aes(x = sex, fill = disease_status)) +
  geom_bar() +
  facet_grid(icu_status ~ .) +
  geom_text(aes(label = ..count..), stat = "count", position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values = c("disease state: COVID-19" = "#f69F00", "disease state: non-COVID-19" = "#5654E9")) +
  labs(x = "sex", fill = "disease_status", title = "Occupation by ICU Status, Sex, and Disease Status") +
  theme_minimal()
```

